oneup_flysystem:
    adapters:
        image:
            local:
                location: '%kernel.project_dir%/%env(resolve:IMAGE_DIR)%'
        public_image:
            local:
                location: '%kernel.project_dir%/%env(resolve:PUBLIC_IMAGE_DIR)%'
    filesystems:
        image:
            adapter: image
            visibility: private
            alias: flysystem_image
